language: go
sudo: false
go_import_path: github.com/hellish/oauth-redis
go:
  - 1.14
services:
  - redis-server
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)